CREATE TABLE "users" (
  "user_id" SERIAL PRIMARY KEY,
  "first_name" varchar NOT NULL,
  "last_name" varchar NOT NULL,
  "address" varchar NOT NULL,
  "phone" varchar NOT NULL,
  "email" varchar UNIQUE NOT NULL,
  "password" bytea NOT NULL,
  "deposit" numeric(15,2) NOT NULL DEFAULT 0,
  "activated" boolean NOT NULL,
  "version" int NOT NULL DEFAULT 1,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL
);

CREATE TABLE "tokens" (
  "token_hash" bytea PRIMARY KEY,
  "user_id" int NOT NULL,
  "expiry" timestamptz NOT NULL,
  "scope" varchar NOT NULL
);

CREATE TABLE "games" (
  "game_id" SERIAL PRIMARY KEY,
  "title" varchar NOT NULL,
  "description" varchar NOT NULL,
  "year" int NOT NULL,
  "genres" text[] NOT NULL,
  "price" numeric(15,2) NOT NULL,
  "stock" int NOT NULL DEFAULT 0,
  "version" int NOT NULL DEFAULT 1,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL
);

CREATE TABLE "carts" (
  "cart_id" SERIAL PRIMARY KEY,
  "user_id" int NOT NULL,
  "game_id" int NOT NULL,
  "quantity" int NOT NULL,
  "sub_total" numeric(15,2) NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL
);

CREATE TABLE "orders" (
  "order_id" SERIAL PRIMARY KEY,
  "user_id" int NOT NULL,
  "status" varchar NOT NULL,
  "total_price" numeric(15,2) NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL
);

CREATE TABLE "payments" (
  "payment_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" int NOT NULL,
  "status" varchar NOT NULL,
  "payment_method" varchar NOT NULL,
  "invoice_id" varchar NOT NULL DEFAULT '',
  "invoice_url" varchar NOT NULL DEFAULT '',
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL
);

CREATE TABLE "order_details" (
  "order_detail_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" int NOT NULL,
  "game_id" int NOT NULL,
  "quantity" int NOT NULL,
  "sub_total" numeric(15,2) NOT NULL
);

ALTER TABLE "payments" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("order_id");

ALTER TABLE "order_details" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("order_id");

ALTER TABLE "order_details" ADD FOREIGN KEY ("game_id") REFERENCES "games" ("game_id");

ALTER TABLE "tokens" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");

ALTER TABLE "carts" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");

ALTER TABLE "carts" ADD FOREIGN KEY ("game_id") REFERENCES "games" ("game_id");

ALTER TABLE "orders" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");